"""Tests for the subscribable per-trip iCal feed.

Covers: the token round-trip (backend/auth.py's create_ical_token /
verify_ical_token), the public feed endpoint bypassing auth middleware
entirely (backend/routers/calendar.py + main.py's _PUBLIC_PREFIXES), trip
isolation (a token only ever serves its own trip), and the actual ICS
content generated by backend/ical_export.py (floating times for timed
items, all-day exclusive-end spans for accommodation, RFC 5545 escaping).
"""
import re

import pytest
from fastapi.testclient import TestClient
from sqlmodel import Session

from backend import auth, permissions
from backend.models import Trip


def _make_trip(client: TestClient, name="ICS Trip"):
    return client.post("/trips/", json={"name": name}).json()


def _make_stop(client: TestClient, trip_id, location="Paris"):
    return client.post(f"/trips/{trip_id}/stops", json={"location": location}).json()


def _make_item(client: TestClient, stop_id, **kwargs):
    return client.post(f"/stops/{stop_id}/items", json=kwargs).json()


def _token_from_url(url: str) -> str:
    m = re.search(r"/calendar/(.+)\.ics$", url)
    assert m, f"unexpected calendar-url shape: {url}"
    return m.group(1)


# ── Token round-trip ────────────────────────────────────────────────────────

def test_create_and_verify_ical_token_round_trip():
    token = auth.create_ical_token(42)
    assert auth.verify_ical_token(token) == 42


def test_verify_ical_token_rejects_garbage():
    assert auth.verify_ical_token("not-a-jwt-at-all") is None


def test_verify_ical_token_rejects_wrong_scope():
    from jose import jwt as jose_jwt
    token = jose_jwt.encode({"trip_id": 1, "scope": "something_else"}, auth.JWT_SECRET, algorithm=auth.JWT_ALGORITHM)
    assert auth.verify_ical_token(token) is None


def test_verify_ical_token_rejects_wrong_secret():
    from jose import jwt as jose_jwt
    token = jose_jwt.encode({"trip_id": 1, "scope": "ical"}, "not-the-real-secret", algorithm=auth.JWT_ALGORITHM)
    assert auth.verify_ical_token(token) is None


def test_verify_ical_token_rejects_missing_trip_id():
    from jose import jwt as jose_jwt
    token = jose_jwt.encode({"scope": "ical"}, auth.JWT_SECRET, algorithm=auth.JWT_ALGORITHM)
    assert auth.verify_ical_token(token) is None


# ── calendar-url endpoint ────────────────────────────────────────────────────

def test_calendar_url_returns_working_token(client: TestClient):
    trip = _make_trip(client)
    r = client.get(f"/trips/{trip['id']}/calendar-url")
    assert r.status_code == 200
    url = r.json()["url"]
    assert url.startswith("/calendar/") and url.endswith(".ics")
    trip_id = auth.verify_ical_token(_token_from_url(url))
    assert trip_id == trip["id"]


def test_calendar_url_requires_at_least_viewer_access(client: TestClient, session: Session, monkeypatch):
    # Insert the trip directly (bypassing the client) so no TripMembership
    # row is created for anyone, then require a real, membership-less caller.
    trip = Trip(name="No Access")
    session.add(trip)
    session.commit()
    session.refresh(trip)

    monkeypatch.setattr(auth, "AUTH_ENABLED", True)
    monkeypatch.setattr(permissions, "AUTH_ENABLED", True)
    token = auth.create_jwt({"email": "stranger@example.com"})
    r = client.get(f"/trips/{trip.id}/calendar-url", headers={"Authorization": f"Bearer {token}"})
    # No membership row for this caller → 404, same "don't leak existence"
    # behaviour as every other trip endpoint (backend/permissions.py).
    assert r.status_code == 404


# ── Public feed endpoint: no auth required ──────────────────────────────────

def test_feed_returns_200_without_auth_headers_for_valid_token(client: TestClient, monkeypatch):
    trip = _make_trip(client)
    url = client.get(f"/trips/{trip['id']}/calendar-url").json()["url"]

    # Flip auth on globally *after* minting the token/trip, to prove the feed
    # endpoint is exempt from the Bearer-token requirement the middleware
    # would otherwise enforce on every other path.
    monkeypatch.setattr(auth, "AUTH_ENABLED", True)
    r = client.get(url)  # deliberately no Authorization header
    assert r.status_code == 200
    assert r.headers["content-type"].startswith("text/calendar")
    assert r.text.startswith("BEGIN:VCALENDAR")


def test_feed_rejects_garbage_token_with_404(client: TestClient):
    r = client.get("/calendar/complete-garbage.ics")
    assert r.status_code == 404


def test_feed_rejects_forged_token_with_404(client: TestClient):
    from jose import jwt as jose_jwt
    forged = jose_jwt.encode({"trip_id": 1, "scope": "ical"}, "wrong-secret", algorithm=auth.JWT_ALGORITHM)
    r = client.get(f"/calendar/{forged}.ics")
    assert r.status_code == 404


def test_feed_404s_for_deleted_trip(client: TestClient):
    trip = _make_trip(client)
    token = auth.create_ical_token(trip["id"])
    client.delete(f"/trips/{trip['id']}")
    r = client.get(f"/calendar/{token}.ics")
    assert r.status_code == 404


# ── Trip isolation ───────────────────────────────────────────────────────────

def test_token_for_trip_a_does_not_serve_trip_b(client: TestClient):
    trip_a = _make_trip(client, "Trip A")
    trip_b = _make_trip(client, "Trip B")
    stop_a = _make_stop(client, trip_a["id"], "A-ville")
    stop_b = _make_stop(client, trip_b["id"], "B-ville")
    _make_item(client, stop_a["id"], kind="activity", name="Only In A", scheduled_at="2026-07-01T09:00:00")
    _make_item(client, stop_b["id"], kind="activity", name="Only In B", scheduled_at="2026-07-01T09:00:00")

    url_a = client.get(f"/trips/{trip_a['id']}/calendar-url").json()["url"]
    ics_a = client.get(url_a).text

    assert "Only In A" in ics_a
    assert "Only In B" not in ics_a


# ── ICS content ──────────────────────────────────────────────────────────────

@pytest.fixture
def seeded_trip_ics(client: TestClient):
    """A trip with a flight (timed, floating DTSTART/DTEND), an accommodation
    (all-day, exclusive DTEND), and an undated note (must produce no VEVENT)."""
    trip = _make_trip(client, "Seeded")
    stop = _make_stop(client, trip["id"], "Paris")

    _make_item(
        client, stop["id"],
        kind="flight", name="Flight, direct",
        details={
            "depart_time": "2026-07-20T10:30:00",
            "arrive_time": "2026-07-20T13:45:00",
            "origin": "CDG", "destination": "JFK",
            "booking_ref": "ABC123",
        },
    )
    _make_item(
        client, stop["id"],
        kind="accommodation", name="Hotel Foo",
        details={
            "checkin": "2026-07-20T15:00:00",
            "checkout": "2026-07-23T11:00:00",
            "location": "1 Rue de Paris",
        },
    )
    _make_item(client, stop["id"], kind="note", name="Undated note")

    url = client.get(f"/trips/{trip['id']}/calendar-url").json()["url"]
    return client.get(url).text


def test_vevent_count_skips_undated_items(seeded_trip_ics):
    assert seeded_trip_ics.count("BEGIN:VEVENT") == 2
    assert "Undated note" not in seeded_trip_ics


def test_flight_emits_floating_datetime(seeded_trip_ics):
    # No trailing Z, no TZID — floating local time (see CLAUDE.md's timezone
    # section + backend/ical_export.py's module docstring for why).
    assert "DTSTART:20260720T103000" in seeded_trip_ics
    assert "DTEND:20260720T134500" in seeded_trip_ics
    assert "DTSTART:20260720T103000Z" not in seeded_trip_ics
    assert "TZID" not in seeded_trip_ics


def test_accommodation_is_all_day_with_exclusive_end(seeded_trip_ics):
    assert "DTSTART;VALUE=DATE:20260720" in seeded_trip_ics
    assert "DTEND;VALUE=DATE:20260723" in seeded_trip_ics


def test_escapes_comma_in_summary(seeded_trip_ics):
    # RFC 5545 requires literal commas in TEXT values to be escaped.
    assert r"SUMMARY:Flight\, direct" in seeded_trip_ics
    assert "SUMMARY:Flight, direct" not in seeded_trip_ics


def test_stable_uid_per_item(client: TestClient):
    trip = _make_trip(client)
    stop = _make_stop(client, trip["id"])
    item = _make_item(client, stop["id"], kind="activity", name="Museum", scheduled_at="2026-07-01T09:00:00")
    url = client.get(f"/trips/{trip['id']}/calendar-url").json()["url"]
    ics = client.get(url).text
    assert f"UID:item-{item['id']}@travelcompanion" in ics
