"""add packing bag and packingitem

Revision ID: 585f3ca060b4
Revises: bad353c9cafd
Create Date: 2026-07-01 08:49:28.275119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '585f3ca060b4'
down_revision: Union[str, Sequence[str], None] = 'bad353c9cafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bag_trip_id'), ['trip_id'], unique=False)

    op.create_table('packingitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('packed_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bag_id'], ['bag.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packingitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packingitem_owner_email'), ['owner_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_packingitem_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packingitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packingitem_trip_id'))
        batch_op.drop_index(batch_op.f('ix_packingitem_owner_email'))

    op.drop_table('packingitem')
    with op.batch_alter_table('bag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bag_trip_id'))

    op.drop_table('bag')
    # ### end Alembic commands ###
