"""add item attachment table

Revision ID: 5d95873f18a6
Revises: 4b1208e39c3e
Create Date: 2026-07-08 01:28:49.422664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '5d95873f18a6'
down_revision: Union[str, Sequence[str], None] = '4b1208e39c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemattachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itineraryitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itemattachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itemattachment_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itemattachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itemattachment_item_id'))

    op.drop_table('itemattachment')
    # ### end Alembic commands ###
