"""add push subscription and notification log

Revision ID: 69bae137ef49
Revises: d24eba6e3baf
Create Date: 2026-07-01 16:00:46.102632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '69bae137ef49'
down_revision: Union[str, Sequence[str], None] = 'd24eba6e3baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificationlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificationlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificationlog_item_id'), ['item_id'], unique=False)

    op.create_table('pushsubscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('p256dh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pushsubscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pushsubscription_endpoint'), ['endpoint'], unique=True)
        batch_op.create_index(batch_op.f('ix_pushsubscription_user_email'), ['user_email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pushsubscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pushsubscription_user_email'))
        batch_op.drop_index(batch_op.f('ix_pushsubscription_endpoint'))

    op.drop_table('pushsubscription')
    with op.batch_alter_table('notificationlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificationlog_item_id'))

    op.drop_table('notificationlog')
    # ### end Alembic commands ###
