"""add location timezone cache

Revision ID: 76ddd8de06c7
Revises: a465e2ede690
Create Date: 2026-07-16 22:55:37.334938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '76ddd8de06c7'
down_revision: Union[str, Sequence[str], None] = 'a465e2ede690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locationtimezone',
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iana_zone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('location')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locationtimezone')
    # ### end Alembic commands ###
