"""add user document vault

Revision ID: 76fc2cc70d83
Revises: 73ba3ad1fc33
Create Date: 2026-07-11 15:39:39.142098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '76fc2cc70d83'
down_revision: Union[str, Sequence[str], None] = '73ba3ad1fc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_number_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userdocument', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userdocument_user_email'), ['user_email'], unique=False)

    op.create_table('userdocumentfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['userdocument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userdocumentfile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userdocumentfile_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdocumentfile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userdocumentfile_document_id'))

    op.drop_table('userdocumentfile')
    with op.batch_alter_table('userdocument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userdocument_user_email'))

    op.drop_table('userdocument')
    # ### end Alembic commands ###
