"""add expense table

Revision ID: 8daa59690ec2
Revises: 76ddd8de06c7
Create Date: 2026-07-16 13:52:58.101881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '8daa59690ec2'
down_revision: Union[str, Sequence[str], None] = '76ddd8de06c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('converted_amount', sa.Float(), nullable=True),
    sa.Column('converted_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itineraryitem.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_stop_id'), ['stop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_trip_id'))
        batch_op.drop_index(batch_op.f('ix_expense_stop_id'))
        batch_op.drop_index(batch_op.f('ix_expense_item_id'))

    op.drop_table('expense')
    # ### end Alembic commands ###
