"""add airport coverage cache

Revision ID: 991566abc5c9
Revises: 8daa59690ec2
Create Date: 2026-07-18 14:20:45.879513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '991566abc5c9'
down_revision: Union[str, Sequence[str], None] = '8daa59690ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airportcoverage',
    sa.Column('iata', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('live_updates_ok', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('iata')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airportcoverage')
    # ### end Alembic commands ###
