"""add location timezone country

Revision ID: 9a88f48bcd59
Revises: 717f796118ab
Create Date: 2026-09-16 02:18:34.857835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '9a88f48bcd59'
down_revision: Union[str, Sequence[str], None] = '717f796118ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locationtimezone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locationtimezone', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
