"""add api_token table

Revision ID: a1c2e3f4b5d6
Revises: 991566abc5c9
Create Date: 2026-08-27 21:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'a1c2e3f4b5d6'
down_revision: Union[str, Sequence[str], None] = '991566abc5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'apitoken',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('apitoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apitoken_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_apitoken_user_email'), ['user_email'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('apitoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apitoken_user_email'))
        batch_op.drop_index(batch_op.f('ix_apitoken_jti'))

    op.drop_table('apitoken')
