"""add bag packed flag

Revision ID: a465e2ede690
Revises: e908ba310969
Create Date: 2026-07-13 09:07:46.925077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'a465e2ede690'
down_revision: Union[str, Sequence[str], None] = 'e908ba310969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default=false so existing rows get a value before the NOT NULL
    # constraint applies (Postgres rejects adding a NOT NULL column with no
    # default to a table that already has rows) -- dropped right after via
    # a second batch op, matching SQLModel's application-level-only default
    # (no other bag column carries a server default).
    with op.batch_alter_table('bag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packed', sa.Boolean(), nullable=False, server_default=sa.false()))
    with op.batch_alter_table('bag', schema=None) as batch_op:
        batch_op.alter_column('packed', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('bag', schema=None) as batch_op:
        batch_op.drop_column('packed')
