"""add traveler table

Revision ID: cb88a616d94d
Revises: a1060f3d2f3b
Create Date: 2026-09-14 03:06:53.549881

D7 backfill (docs/plans/plan-17-travelers.md): inserts one Traveler row per
existing TripMembership so the switch to traveler-based personal totals
(plan-17b) doesn't zero out everyone's lifetime distance the moment this
deploys — the owner then prunes the members who weren't actually traveling.
Written with raw op.execute/sa.table (no ORM imports in migrations, per
docs/plans/README.md convention 5) and guarded with a NOT EXISTS so a re-run
(or a downgrade/upgrade round-trip) never duplicates rows.
"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'cb88a616d94d'
down_revision: Union[str, Sequence[str], None] = 'a1060f3d2f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age_band', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('passport_expiry', sa.DateTime(), nullable=True),
    sa.Column('profile_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traveler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traveler_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traveler_user_email'), ['user_email'], unique=False)

    # ### end Alembic commands ###

    # ── D7 backfill: one Traveler per existing TripMembership, idempotent ──
    backfill_travelers(op.get_bind())


def backfill_travelers(conn) -> None:
    rows = conn.execute(sa.text("SELECT trip_id, user_email FROM tripmembership")).fetchall()
    now = datetime.utcnow()
    for trip_id, email in rows:
        display_name = (email or "").split("@")[0] or email
        conn.execute(
            sa.text(
                "INSERT INTO traveler (trip_id, user_email, display_name, created_at, updated_at) "
                "SELECT :t, :e, :n, :now, :now WHERE NOT EXISTS "
                "(SELECT 1 FROM traveler WHERE trip_id = :t AND user_email = :e)"
            ),
            {"t": trip_id, "e": email, "n": display_name, "now": now},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traveler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traveler_user_email'))
        batch_op.drop_index(batch_op.f('ix_traveler_trip_id'))

    op.drop_table('traveler')
    # ### end Alembic commands ###
