"""add bag parent_id for nesting

Revision ID: d24eba6e3baf
Revises: 585f3ca060b4
Create Date: 2026-07-01 09:45:27.165345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'd24eba6e3baf'
down_revision: Union[str, Sequence[str], None] = '585f3ca060b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Named FK so SQLite batch mode (which recreates the table) is happy.
    with op.batch_alter_table('bag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bag_parent_id_bag', 'bag', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bag', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bag_parent_id_bag', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
