"""add user document holder data

Revision ID: e908ba310969
Revises: 76fc2cc70d83
Create Date: 2026-07-11 23:26:05.067749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'e908ba310969'
down_revision: Union[str, Sequence[str], None] = '76fc2cc70d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdocument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holder_data_encrypted', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdocument', schema=None) as batch_op:
        batch_op.drop_column('holder_data_encrypted')

    # ### end Alembic commands ###
