"""baseline schema

Revision ID: f009fcc9537f
Revises: 
Create Date: 2026-06-30 16:54:41.736113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'f009fcc9537f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestedemail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('from_addr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_addr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parse_error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('op', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('changed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itemhistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itemhistory_item_id'), ['item_id'], unique=False)

    op.create_table('pendingchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_email_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('op', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_item_id', sa.Integer(), nullable=True),
    sa.Column('suggested_stop_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('activity', 'restaurant', 'note', 'accommodation', 'flight', 'cycling', 'rail', 'walk', 'transfer', 'tour', 'food', 'purchase', 'show', 'hire', name='itemkind'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'applied', 'discarded', name='pendingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pendingchange', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pendingchange_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_pendingchange_trip_id'), ['trip_id'], unique=False)

    op.create_table('processeddocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processeddocument', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processeddocument_cache_key'), ['cache_key'], unique=False)

    op.create_table('trip',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userimporttoken',
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    with op.batch_alter_table('userimporttoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userimporttoken_token'), ['token'], unique=False)

    op.create_table('stop',
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arrive', sa.DateTime(), nullable=True),
    sa.Column('depart', sa.DateTime(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lng', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'confirmed', 'completed', 'cancelled', name='stopstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('accommodation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accommodation_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accommodation_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('check_in', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('check_out', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tripmembership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='triprole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tripmembership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tripmembership_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tripmembership_user_email'), ['user_email'], unique=False)

    op.create_table('itineraryitem',
    sa.Column('kind', sa.Enum('activity', 'restaurant', 'note', 'accommodation', 'flight', 'cycling', 'rail', 'walk', 'transfer', 'tour', 'food', 'purchase', 'show', 'hire', name='itemkind'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'skipped', name='itemstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itineraryitem')
    with op.batch_alter_table('tripmembership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tripmembership_user_email'))
        batch_op.drop_index(batch_op.f('ix_tripmembership_trip_id'))

    op.drop_table('tripmembership')
    op.drop_table('stop')
    with op.batch_alter_table('userimporttoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userimporttoken_token'))

    op.drop_table('userimporttoken')
    op.drop_table('trip')
    with op.batch_alter_table('processeddocument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processeddocument_cache_key'))

    op.drop_table('processeddocument')
    with op.batch_alter_table('pendingchange', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pendingchange_trip_id'))
        batch_op.drop_index(batch_op.f('ix_pendingchange_created_by'))

    op.drop_table('pendingchange')
    with op.batch_alter_table('itemhistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itemhistory_item_id'))

    op.drop_table('itemhistory')
    op.drop_table('ingestedemail')
    # ### end Alembic commands ###
